In [19]:
import pandas as pd

df = pd.read_csv("movies_metadata.csv")


df

/var/folders/qc/7382bn3j7vq46cnb3_4lsqk40000gn/T/ipykernel_946/473839123.py:3: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("movies_metadata.csv")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [20]:
df = df[df['original_language'] == "en"]
df = df[df["vote_count"].notna()]
df = df.sort_values("vote_count", ascending=False).iloc[:10000]

In [21]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
15480,False,NaN,160000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://inceptionmovie.warnerbros.com/,27205,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",...,2010-07-14,8.255328e+08,148.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Your mind is the scene of the crime.,Inception,False,8.1,14075.0
12481,False,"{'id': 263, 'name': 'The Dark Knight Collectio...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,155,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,...,2008-07-16,1.004558e+09,152.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Why So Serious?,The Dark Knight,False,8.3,12269.0
14551,False,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",...,2009-12-10,2.787965e+09,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Enter the World of Pandora.,Avatar,False,7.2,12114.0
17818,False,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,24428,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,...,2012-04-25,1.519558e+09,143.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some assembly required.,The Avengers,False,7.4,12000.0
26564,False,"{'id': 448150, 'name': 'Deadpool Collection', ...",58000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.foxmovies.com/movies/deadpool,293660,tt1431045,en,Deadpool,Deadpool tells the origin story of former Spec...,...,2016-02-09,7.831130e+08,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Witness the beginning of a happy ending,Deadpool,False,7.4,11444.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4486,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,12774,tt0097714,en,Last Exit to Brooklyn,A gritty Brooklyn story about union corruption...,...,1989-10-11,0.000000e+00,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Novel That Shocked The World Is Now A Movie,Last Exit to Brooklyn,False,6.1,28.0
7740,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,21544,tt0314431,en,Hope Springs,British artist Colin Ware discovers that his f...,...,2003-05-09,0.000000e+00,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The problem every man dreams of... a choice.,Hope Springs,False,5.1,28.0
18512,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}]",NaN,26223,tt0960741,en,The Canyon,A survival story about a honeymooning couple w...,...,2009-10-23,0.000000e+00,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Surviving is just the beginning,The Canyon,False,5.9,28.0
20428,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,124461,tt2044729,en,A Glimpse Inside the Mind of Charles Swan III,"Charles Swan III, a successful graphic designe...",...,2012-11-15,0.000000e+00,86.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Reality Is Overrated,A Glimpse Inside the Mind of Charles Swan III,False,4.2,28.0
10694,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,44345,tt0428441,en,The Cutting Edge: The Magic of Movie Editing,Documentary about the art of film editing. Cli...,...,2004-01-01,0.000000e+00,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Cutting Edge: The Magic of Movie Editing,False,7.1,28.0

In [25]:
import pandas as pd
import json
import ast
import chromadb
from tqdm import tqdm
from collections import defaultdict

# Filter rows
df = df[df["overview"].notna()].copy()
print(f"{len(df)} movies with overview loaded")

# Parse genres
def parse_genres(genres_str):
    try:
        if pd.isna(genres_str):
            return []

        # Handle strings like:
        # "[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]"
        genres = ast.literal_eval(genres_str)

        if not isinstance(genres, list):
            return []

        return [g["name"] for g in genres if isinstance(g, dict) and "name" in g]
    except Exception:
        return []

tqdm.pandas(desc="Parsing genres")
df["genre_names"] = df["genres"].progress_apply(parse_genres)

# Optional quick sanity check
print(df[["genres", "genre_names"]].head())

# Prepare documents
documents = df["overview"].tolist()
ids = [f"movie_{i}" for i in range(len(df))]

metadatas = []
genre_to_ids = defaultdict(list)

# Build metadata and genre index
for i, (_, row) in enumerate(
    tqdm(df.iterrows(), total=len(df), desc="Building metadata + genre index")
):
    movie_id = ids[i]
    genres = row["genre_names"]

    metadatas.append({
        "title": row["original_title"],
        "original_language": row["original_language"],
        "genres_json": json.dumps(genres)
    })

    for genre in genres:
        genre_to_ids[genre].append(movie_id)

# Initialize Chroma
print("Initializing Chroma DB...")
client = chromadb.PersistentClient("./chroma")

try:
    client.delete_collection("movies_database")
except Exception:
    pass

collection = client.create_collection(name="movies_database")

# Upload in batches
batch_size = 500

for i in tqdm(range(0, len(documents), batch_size), desc="Uploading to Chroma"):
    collection.add(
        documents=documents[i:i+batch_size],
        metadatas=metadatas[i:i+batch_size],
        ids=ids[i:i+batch_size],
    )

print(f"\nAdded {collection.count()} movies to the 'movies' collection")
print(f"Indexed {len(genre_to_ids)} genres")
print("Example genres:", list(genre_to_ids.keys())[:10])

10000 movies with overview loaded

Parsing genres: 100%|██████████| 10000/10000 [00:00<00:00, 58144.31it/s]

                                                  genres  \
15480  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
12481  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...
14551  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
17818  [{'id': 878, 'name': 'Science Fiction'}, {'id'...
26564  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...

                                             genre_names
15480  [Action, Thriller, Science Fiction, Mystery, A...
12481                   [Drama, Action, Crime, Thriller]
14551      [Action, Adventure, Fantasy, Science Fiction]
17818               [Science Fiction, Action, Adventure]
26564                        [Action, Adventure, Comedy]

Building metadata + genre index: 100%|██████████| 10000/10000 [00:00<00:00, 67244.11it/s]

Initializing Chroma DB...

Uploading to Chroma: 100%|██████████| 20/20 [04:02<00:00, 12.13s/it]

Added 10000 movies to the 'movies' collection
Indexed 20 genres
Example genres: ['Action', 'Thriller', 'Science Fiction', 'Mystery', 'Adventure', 'Drama', 'Crime', 'Fantasy', 'Comedy', 'Western']

In [26]:
results = collection.query(
    query_texts=["A romatic movie with my girlfriend"],
    n_results=3,
)

for i, doc in enumerate(results["documents"][0]):
    print(f"Result {i + 1}:")
    print(doc)
    print()

Result 1:
In the middle of this amusing thriller is a relationship between two different types of females, one is a well know British author and the other is a sex-crazed French teen. The two get into some relationship trouble while living together in this film of psychological imagery and an erotic exploration of the female body.

Result 2:
A dialogue marathon of a film, this fairytale love story of an American boy and French girl. During a day and a night together in Vienna their two hearts collide.

Result 3:
Revolves around a young couple and their friends struggling with adulthood and issues of relationships and commitment. Based on the 2001 Italian film L'ultimo bacio, directed by Gabriele Muccino.

In [27]:
results

{'ids': [['movie_4164', 'movie_1112', 'movie_4655']],
 'embeddings': None,
 'documents': [['In the middle of this amusing thriller is a relationship between two different types of females, one is a well know British author and the other is a sex-crazed French teen. The two get into some relationship trouble while living together in this film of psychological imagery and an erotic exploration of the female body.',
   'A dialogue marathon of a film, this fairytale love story of an American boy and French girl. During a day and a night together in Vienna their two hearts collide.',
   "Revolves around a young couple and their friends struggling with adulthood and issues of relationships and commitment. Based on the 2001 Italian film L'ultimo bacio, directed by Gabriele Muccino."]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'title': 'Swimming Pool',
    'original_language': 'en',
    'genres_json': '["Thriller", "Crime"]'},
   {'title': 'Before Sunrise',
    'original_language': 'en',
    'genres_json': '["Drama", "Romance"]'},
   {'title': 'The Last Kiss',
    'original_language': 'en',
    'genres_json': '["Comedy", "Drama", "Romance"]'}]],
 'distances': [[0.8389512300491333, 0.8801540732383728, 0.885678768157959]]}